/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as PlansRefIdIndexRouteImport } from './routes/plans.$refId.index'
import { Route as PlansRefIdEmailRouteImport } from './routes/plans.$refId.email'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRefIdIndexRoute = PlansRefIdIndexRouteImport.update({
  id: '/plans/$refId/',
  path: '/plans/$refId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRefIdEmailRoute = PlansRefIdEmailRouteImport.update({
  id: '/plans/$refId/email',
  path: '/plans/$refId/email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/upload': typeof UploadRoute
  '/plans/': typeof PlansIndexRoute
  '/plans/$refId/email': typeof PlansRefIdEmailRoute
  '/plans/$refId/': typeof PlansRefIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/upload': typeof UploadRoute
  '/plans': typeof PlansIndexRoute
  '/plans/$refId/email': typeof PlansRefIdEmailRoute
  '/plans/$refId': typeof PlansRefIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/upload': typeof UploadRoute
  '/plans/': typeof PlansIndexRoute
  '/plans/$refId/email': typeof PlansRefIdEmailRoute
  '/plans/$refId/': typeof PlansRefIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reports'
    | '/rules'
    | '/upload'
    | '/plans/'
    | '/plans/$refId/email'
    | '/plans/$refId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/reports'
    | '/rules'
    | '/upload'
    | '/plans'
    | '/plans/$refId/email'
    | '/plans/$refId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/reports'
    | '/rules'
    | '/upload'
    | '/plans/'
    | '/plans/$refId/email'
    | '/plans/$refId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ReportsRoute: typeof ReportsRoute
  RulesRoute: typeof RulesRoute
  UploadRoute: typeof UploadRoute
  PlansIndexRoute: typeof PlansIndexRoute
  PlansRefIdEmailRoute: typeof PlansRefIdEmailRoute
  PlansRefIdIndexRoute: typeof PlansRefIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$refId/': {
      id: '/plans/$refId/'
      path: '/plans/$refId'
      fullPath: '/plans/$refId/'
      preLoaderRoute: typeof PlansRefIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$refId/email': {
      id: '/plans/$refId/email'
      path: '/plans/$refId/email'
      fullPath: '/plans/$refId/email'
      preLoaderRoute: typeof PlansRefIdEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ReportsRoute: ReportsRoute,
  RulesRoute: RulesRoute,
  UploadRoute: UploadRoute,
  PlansIndexRoute: PlansIndexRoute,
  PlansRefIdEmailRoute: PlansRefIdEmailRoute,
  PlansRefIdIndexRoute: PlansRefIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
